name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Upgrade
      run: sudo apt-get upgrade && sudo apt-get update
    - name: Install x11
      run: sudo apt install libx11-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
